---
kind: pipeline
type: docker
name: Install elasticsearch cluster (prod)

clone:
  depth: 1

steps:

  - name: deploy
    image: docker.nexus.diesel.net/drone-ansible:5.3.0
    environment:
      ANSIBLE_CONFIG: .ansible/ansible.cfg
      ELASTIC_PASSWORD:
        from_secret: elastic_pass
    settings:
      galaxy: .ansible/roles/requirements.yaml
      playbook: .ansible/deploy.yaml
      inventory: .ansible/inventories/production
      private_key:
        from_secret: automation_id_rsa
      vault_password:
        from_secret: ansible_vault_password
      extra_vars: version=production


trigger:
  branch:
    - stable
  event:
    - push
...
