- hosts: elastic
  roles:
    - common

  tasks:

    - include_role:
        name: docker
        tasks_from: stack_teardown
      when: clean_install

    - name: Remove data directory (clean install)
      file: 
        path: '{{ data_dir }}'
        state: absent
      become: yes
      when: clean_install

    - include_role:
        name: common
        tasks_from: make_config_dir

    - include_role:
        name: common
        tasks_from: make_data_dir

    - name: 'Render instances.yml.j2 file'
      template:
        src: instances.yml.j2
        dest: '{{ config_dir }}/instances.yml'

    - name: 'Ensure node data directories exists'
      file:
        state: directory
        path: '{{ data_dir }}/{{ item }}'
        mode: '0777'
      loop_control:
        label: '{{ data_dir }}/{{ item }}'
      loop: '{{ elastic_nodes }}'

    - name: Persist vm.max_map_count to at least 262144 (required)
      sysctl:
        name: vm.max_map_count
        value: '262144'
        state: present
      become: yes

    - name: Disable swapping
      sysctl:
        name: vm.swappiness
        value: '0'
        state: present
      become: yes

    - include_role:
        name: docker
        tasks_from: stack_deploy
